version: '3'
services:
  pseudo-app:
    container_name: pseudo-app
    build:
      context: .
    ports:
      - 5000:5000
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus/config.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - pseudo-app
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
    - ./monitoring/grafana/config.ini:/etc/grafana/grafana.ini
    - ./monitoring/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
    - ./monitoring/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
    - 3000:3000
    depends_on:
    - prometheus