global:
  scrape_interval: 3s
  external_labels:
    monitor: "pseudo-app"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "pseudo-app"
    static_configs:
    - targets: ["pseudo-app:5000"]