---
- name: Install
  hosts: all
  tasks:
  - name: Install python3-pip
    become: yes
    apt:
      name: python3-pip
      update_cache: true
  - name: Install Python Modules
    pip:
      requirements: "/data/requirements.txt"
  - name: Install Python WSGI server
    pip:
      name: gunicorn
  - name: Start WSGI server
    shell: "python3 -m gunicorn -w 4 -b 0.0.0.0:5000 'app:app' >/dev/null 2>&1 &"
    environment:
      PYTHONPATH: /data/
