 ---
  - hosts: local
  connection: local
  tasks:
    - name: Install python3-pip
      apt:
        name: python3-pip
        update_cache: true
    - name: Install Python Modules
        pip: 
          requirements: "/data/requirements.txt"
    - name: Start flask application
    shell: "python3 -m flask run --host=0.0.0.0"
      environment:
      FLASK_APP: /data/app.py