---
- name: Install
  hosts: all
  tasks:
  - name: Install python3-pip
    become: yes
    apt:
      name: python3-pip
      update_cache: true
  - name: Install Python Modules
    pip:
      requirements: "/data/requirements.txt"
  - name: Start flask application
    shell: "python3 -m flask run --host=0.0.0.0 >/dev/null 2>&1 &"
    environment:
      FLASK_APP: /data/app.py
